logging:
  level:
    root: INFO
    io.prada.listener: DEBUG
    org.apache.coyote.http11: WARN
    org.springframework.amqp: WARN

settings:
  use-position-request: true
  balanceType: "BALANCE"
  logs:
    bnb-events: true
#    bnb-responses: true
  publisher:
    amq: false
    telegram: false

telegram:
  botToken: ${TELEGRAM_BOT_TOKEN}
  chatId: ${TELEGRAM_CHAT_ID}

server:
  port: 8070
  shutdown: graceful

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: "listener"
  lifecycle.timeout-per-shutdown-phase: 30s
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: none
    open-in-view: false
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    virtual-host: ${RABBITMQ_VHOST}
    template:
      default-receive-queue: binance-fum
  flyway:
    enabled: false
#    locations: classpath:db/migration
#    baseline-on-migrate: true
#    validate-on-migrate: false

bnb-config:
  publicKey: ${BINANCE_API_KEY}
  privateKey: ${BINANCE_SECRET_KEY}
